// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package multimedia

import (
	"bytes"
	"context"
	"fmt"
	"io/ioutil"
	"math"
	"net/http"
	"net/url"
	"time"

	"cloud.google.com/go/longrunning"
	lroauto "cloud.google.com/go/longrunning/autogen"
	multimediapb "github.com/animeapis/go-genproto/multimedia/v1alpha1"
	gax "github.com/googleapis/gax-go/v2"
	"google.golang.org/api/googleapi"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	gtransport "google.golang.org/api/transport/grpc"
	httptransport "google.golang.org/api/transport/http"
	longrunningpb "google.golang.org/genproto/googleapis/longrunning"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

var newLightNovelClientHook clientHook

// LightNovelCallOptions contains the retry settings for each method of LightNovelClient.
type LightNovelCallOptions struct {
	GetLightNovel        []gax.CallOption
	ListLightNovels      []gax.CallOption
	CreateLightNovel     []gax.CallOption
	UpdateLightNovel     []gax.CallOption
	DeleteLightNovel     []gax.CallOption
	ReconcileLightNovels []gax.CallOption
}

func defaultLightNovelGRPCClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("multimedia.animeapis.com:443"),
		internaloption.WithDefaultMTLSEndpoint("multimedia.animeapis.com:443"),
		internaloption.WithDefaultAudience("https://multimedia.animeapis.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		internaloption.EnableJwtWithScope(),
		option.WithGRPCDialOption(grpc.WithDefaultCallOptions(
			grpc.MaxCallRecvMsgSize(math.MaxInt32))),
	}
}

func defaultLightNovelCallOptions() *LightNovelCallOptions {
	return &LightNovelCallOptions{
		GetLightNovel:        []gax.CallOption{},
		ListLightNovels:      []gax.CallOption{},
		CreateLightNovel:     []gax.CallOption{},
		UpdateLightNovel:     []gax.CallOption{},
		DeleteLightNovel:     []gax.CallOption{},
		ReconcileLightNovels: []gax.CallOption{},
	}
}

func defaultLightNovelRESTCallOptions() *LightNovelCallOptions {
	return &LightNovelCallOptions{
		GetLightNovel:        []gax.CallOption{},
		ListLightNovels:      []gax.CallOption{},
		CreateLightNovel:     []gax.CallOption{},
		UpdateLightNovel:     []gax.CallOption{},
		DeleteLightNovel:     []gax.CallOption{},
		ReconcileLightNovels: []gax.CallOption{},
	}
}

// internalLightNovelClient is an interface that defines the methods available from Multimedia API.
type internalLightNovelClient interface {
	Close() error
	setGoogleClientInfo(...string)
	Connection() *grpc.ClientConn
	GetLightNovel(context.Context, *multimediapb.GetLightNovelRequest, ...gax.CallOption) (*multimediapb.LightNovel, error)
	ListLightNovels(context.Context, *multimediapb.ListLightNovelsRequest, ...gax.CallOption) *LightNovelIterator
	CreateLightNovel(context.Context, *multimediapb.CreateLightNovelRequest, ...gax.CallOption) (*multimediapb.LightNovel, error)
	UpdateLightNovel(context.Context, *multimediapb.UpdateLightNovelRequest, ...gax.CallOption) (*multimediapb.LightNovel, error)
	DeleteLightNovel(context.Context, *multimediapb.DeleteLightNovelRequest, ...gax.CallOption) error
	ReconcileLightNovels(context.Context, *multimediapb.ReconcileLightNovelsRequest, ...gax.CallOption) (*ReconcileLightNovelsOperation, error)
	ReconcileLightNovelsOperation(name string) *ReconcileLightNovelsOperation
}

// LightNovelClient is a client for interacting with Multimedia API.
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type LightNovelClient struct {
	// The internal transport-dependent client.
	internalClient internalLightNovelClient

	// The call options for this service.
	CallOptions *LightNovelCallOptions

	// LROClient is used internally to handle long-running operations.
	// It is exposed so that its CallOptions can be modified if required.
	// Users should not Close this client.
	LROClient *lroauto.OperationsClient
}

// Wrapper methods routed to the internal client.

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *LightNovelClient) Close() error {
	return c.internalClient.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *LightNovelClient) setGoogleClientInfo(keyval ...string) {
	c.internalClient.setGoogleClientInfo(keyval...)
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *LightNovelClient) Connection() *grpc.ClientConn {
	return c.internalClient.Connection()
}

func (c *LightNovelClient) GetLightNovel(ctx context.Context, req *multimediapb.GetLightNovelRequest, opts ...gax.CallOption) (*multimediapb.LightNovel, error) {
	return c.internalClient.GetLightNovel(ctx, req, opts...)
}

func (c *LightNovelClient) ListLightNovels(ctx context.Context, req *multimediapb.ListLightNovelsRequest, opts ...gax.CallOption) *LightNovelIterator {
	return c.internalClient.ListLightNovels(ctx, req, opts...)
}

func (c *LightNovelClient) CreateLightNovel(ctx context.Context, req *multimediapb.CreateLightNovelRequest, opts ...gax.CallOption) (*multimediapb.LightNovel, error) {
	return c.internalClient.CreateLightNovel(ctx, req, opts...)
}

func (c *LightNovelClient) UpdateLightNovel(ctx context.Context, req *multimediapb.UpdateLightNovelRequest, opts ...gax.CallOption) (*multimediapb.LightNovel, error) {
	return c.internalClient.UpdateLightNovel(ctx, req, opts...)
}

func (c *LightNovelClient) DeleteLightNovel(ctx context.Context, req *multimediapb.DeleteLightNovelRequest, opts ...gax.CallOption) error {
	return c.internalClient.DeleteLightNovel(ctx, req, opts...)
}

// ReconcileLightNovels reconcile light novels with the search and knowledge base.
func (c *LightNovelClient) ReconcileLightNovels(ctx context.Context, req *multimediapb.ReconcileLightNovelsRequest, opts ...gax.CallOption) (*ReconcileLightNovelsOperation, error) {
	return c.internalClient.ReconcileLightNovels(ctx, req, opts...)
}

// ReconcileLightNovelsOperation returns a new ReconcileLightNovelsOperation from a given name.
// The name must be that of a previously created ReconcileLightNovelsOperation, possibly from a different process.
func (c *LightNovelClient) ReconcileLightNovelsOperation(name string) *ReconcileLightNovelsOperation {
	return c.internalClient.ReconcileLightNovelsOperation(name)
}

// lightNovelGRPCClient is a client for interacting with Multimedia API over gRPC transport.
//
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type lightNovelGRPCClient struct {
	// Connection pool of gRPC connections to the service.
	connPool gtransport.ConnPool

	// flag to opt out of default deadlines via GOOGLE_API_GO_EXPERIMENTAL_DISABLE_DEFAULT_DEADLINE
	disableDeadlines bool

	// Points back to the CallOptions field of the containing LightNovelClient
	CallOptions **LightNovelCallOptions

	// The gRPC API client.
	lightNovelClient multimediapb.LightNovelServiceClient

	// LROClient is used internally to handle long-running operations.
	// It is exposed so that its CallOptions can be modified if required.
	// Users should not Close this client.
	LROClient **lroauto.OperationsClient

	// The x-goog-* metadata to be sent with each request.
	xGoogMetadata metadata.MD
}

// NewLightNovelClient creates a new light novel service client based on gRPC.
// The returned client must be Closed when it is done being used to clean up its underlying connections.
func NewLightNovelClient(ctx context.Context, opts ...option.ClientOption) (*LightNovelClient, error) {
	clientOpts := defaultLightNovelGRPCClientOptions()
	if newLightNovelClientHook != nil {
		hookOpts, err := newLightNovelClientHook(ctx, clientHookParams{})
		if err != nil {
			return nil, err
		}
		clientOpts = append(clientOpts, hookOpts...)
	}

	disableDeadlines, err := checkDisableDeadlines()
	if err != nil {
		return nil, err
	}

	connPool, err := gtransport.DialPool(ctx, append(clientOpts, opts...)...)
	if err != nil {
		return nil, err
	}
	client := LightNovelClient{CallOptions: defaultLightNovelCallOptions()}

	c := &lightNovelGRPCClient{
		connPool:         connPool,
		disableDeadlines: disableDeadlines,
		lightNovelClient: multimediapb.NewLightNovelServiceClient(connPool),
		CallOptions:      &client.CallOptions,
	}
	c.setGoogleClientInfo()

	client.internalClient = c

	client.LROClient, err = lroauto.NewOperationsClient(ctx, gtransport.WithConnPool(connPool))
	if err != nil {
		// This error "should not happen", since we are just reusing old connection pool
		// and never actually need to dial.
		// If this does happen, we could leak connp. However, we cannot close conn:
		// If the user invoked the constructor with option.WithGRPCConn,
		// we would close a connection that's still in use.
		// TODO: investigate error conditions.
		return nil, err
	}
	c.LROClient = &client.LROClient
	return &client, nil
}

// Connection returns a connection to the API service.
//
// Deprecated: Connections are now pooled so this method does not always
// return the same resource.
func (c *lightNovelGRPCClient) Connection() *grpc.ClientConn {
	return c.connPool.Conn()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *lightNovelGRPCClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", versionGo()}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "grpc", grpc.Version)
	c.xGoogMetadata = metadata.Pairs("x-goog-api-client", gax.XGoogHeader(kv...))
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *lightNovelGRPCClient) Close() error {
	return c.connPool.Close()
}

// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type lightNovelRESTClient struct {
	// The http endpoint to connect to.
	endpoint string

	// The http client.
	httpClient *http.Client

	// LROClient is used internally to handle long-running operations.
	// It is exposed so that its CallOptions can be modified if required.
	// Users should not Close this client.
	LROClient **lroauto.OperationsClient

	// The x-goog-* metadata to be sent with each request.
	xGoogMetadata metadata.MD

	// Points back to the CallOptions field of the containing LightNovelClient
	CallOptions **LightNovelCallOptions
}

// NewLightNovelRESTClient creates a new light novel service rest client.
func NewLightNovelRESTClient(ctx context.Context, opts ...option.ClientOption) (*LightNovelClient, error) {
	clientOpts := append(defaultLightNovelRESTClientOptions(), opts...)
	httpClient, endpoint, err := httptransport.NewClient(ctx, clientOpts...)
	if err != nil {
		return nil, err
	}

	callOpts := defaultLightNovelRESTCallOptions()
	c := &lightNovelRESTClient{
		endpoint:    endpoint,
		httpClient:  httpClient,
		CallOptions: &callOpts,
	}
	c.setGoogleClientInfo()

	lroOpts := []option.ClientOption{
		option.WithHTTPClient(httpClient),
		option.WithEndpoint(endpoint),
	}
	opClient, err := lroauto.NewOperationsRESTClient(ctx, lroOpts...)
	if err != nil {
		return nil, err
	}
	c.LROClient = &opClient

	return &LightNovelClient{internalClient: c, CallOptions: callOpts}, nil
}

func defaultLightNovelRESTClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("https://multimedia.animeapis.com"),
		internaloption.WithDefaultMTLSEndpoint("https://multimedia.animeapis.com"),
		internaloption.WithDefaultAudience("https://multimedia.animeapis.com/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
	}
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *lightNovelRESTClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", versionGo()}, keyval...)
	kv = append(kv, "gapic", getVersionClient(), "gax", gax.Version, "rest", "UNKNOWN")
	c.xGoogMetadata = metadata.Pairs("x-goog-api-client", gax.XGoogHeader(kv...))
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *lightNovelRESTClient) Close() error {
	// Replace httpClient with nil to force cleanup.
	c.httpClient = nil
	return nil
}

// Connection returns a connection to the API service.
//
// Deprecated: This method always returns nil.
func (c *lightNovelRESTClient) Connection() *grpc.ClientConn {
	return nil
}
func (c *lightNovelGRPCClient) GetLightNovel(ctx context.Context, req *multimediapb.GetLightNovelRequest, opts ...gax.CallOption) (*multimediapb.LightNovel, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))

	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).GetLightNovel[0:len((*c.CallOptions).GetLightNovel):len((*c.CallOptions).GetLightNovel)], opts...)
	var resp *multimediapb.LightNovel
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.lightNovelClient.GetLightNovel(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *lightNovelGRPCClient) ListLightNovels(ctx context.Context, req *multimediapb.ListLightNovelsRequest, opts ...gax.CallOption) *LightNovelIterator {
	ctx = insertMetadata(ctx, c.xGoogMetadata)
	opts = append((*c.CallOptions).ListLightNovels[0:len((*c.CallOptions).ListLightNovels):len((*c.CallOptions).ListLightNovels)], opts...)
	it := &LightNovelIterator{}
	req = proto.Clone(req).(*multimediapb.ListLightNovelsRequest)
	it.InternalFetch = func(pageSize int, pageToken string) ([]*multimediapb.LightNovel, string, error) {
		resp := &multimediapb.ListLightNovelsResponse{}
		if pageToken != "" {
			req.PageToken = pageToken
		}
		if pageSize > math.MaxInt32 {
			req.PageSize = math.MaxInt32
		} else if pageSize != 0 {
			req.PageSize = int32(pageSize)
		}
		err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
			var err error
			resp, err = c.lightNovelClient.ListLightNovels(ctx, req, settings.GRPC...)
			return err
		}, opts...)
		if err != nil {
			return nil, "", err
		}

		it.Response = resp
		return resp.GetLightNovels(), resp.GetNextPageToken(), nil
	}
	fetch := func(pageSize int, pageToken string) (string, error) {
		items, nextPageToken, err := it.InternalFetch(pageSize, pageToken)
		if err != nil {
			return "", err
		}
		it.items = append(it.items, items...)
		return nextPageToken, nil
	}

	it.pageInfo, it.nextFunc = iterator.NewPageInfo(fetch, it.bufLen, it.takeBuf)
	it.pageInfo.MaxSize = int(req.GetPageSize())
	it.pageInfo.Token = req.GetPageToken()

	return it
}

func (c *lightNovelGRPCClient) CreateLightNovel(ctx context.Context, req *multimediapb.CreateLightNovelRequest, opts ...gax.CallOption) (*multimediapb.LightNovel, error) {
	ctx = insertMetadata(ctx, c.xGoogMetadata)
	opts = append((*c.CallOptions).CreateLightNovel[0:len((*c.CallOptions).CreateLightNovel):len((*c.CallOptions).CreateLightNovel)], opts...)
	var resp *multimediapb.LightNovel
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.lightNovelClient.CreateLightNovel(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *lightNovelGRPCClient) UpdateLightNovel(ctx context.Context, req *multimediapb.UpdateLightNovelRequest, opts ...gax.CallOption) (*multimediapb.LightNovel, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "light_novel.name", url.QueryEscape(req.GetLightNovel().GetName())))

	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).UpdateLightNovel[0:len((*c.CallOptions).UpdateLightNovel):len((*c.CallOptions).UpdateLightNovel)], opts...)
	var resp *multimediapb.LightNovel
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.lightNovelClient.UpdateLightNovel(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *lightNovelGRPCClient) DeleteLightNovel(ctx context.Context, req *multimediapb.DeleteLightNovelRequest, opts ...gax.CallOption) error {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))

	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).DeleteLightNovel[0:len((*c.CallOptions).DeleteLightNovel):len((*c.CallOptions).DeleteLightNovel)], opts...)
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		_, err = c.lightNovelClient.DeleteLightNovel(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	return err
}

func (c *lightNovelGRPCClient) ReconcileLightNovels(ctx context.Context, req *multimediapb.ReconcileLightNovelsRequest, opts ...gax.CallOption) (*ReconcileLightNovelsOperation, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))

	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).ReconcileLightNovels[0:len((*c.CallOptions).ReconcileLightNovels):len((*c.CallOptions).ReconcileLightNovels)], opts...)
	var resp *longrunningpb.Operation
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.lightNovelClient.ReconcileLightNovels(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return &ReconcileLightNovelsOperation{
		lro: longrunning.InternalNewOperation(*c.LROClient, resp),
	}, nil
}

func (c *lightNovelRESTClient) GetLightNovel(ctx context.Context, req *multimediapb.GetLightNovelRequest, opts ...gax.CallOption) (*multimediapb.LightNovel, error) {
	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1alpha1/%v", req.GetName())

	// Build HTTP headers from client and context metadata.
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))

	headers := buildHeaders(ctx, c.xGoogMetadata, md, metadata.Pairs("Content-Type", "application/json"))
	opts = append((*c.CallOptions).GetLightNovel[0:len((*c.CallOptions).GetLightNovel):len((*c.CallOptions).GetLightNovel)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &multimediapb.LightNovel{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("GET", baseUrl.String(), nil)
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := ioutil.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return maybeUnknownEnum(err)
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}
func (c *lightNovelRESTClient) ListLightNovels(ctx context.Context, req *multimediapb.ListLightNovelsRequest, opts ...gax.CallOption) *LightNovelIterator {
	it := &LightNovelIterator{}
	req = proto.Clone(req).(*multimediapb.ListLightNovelsRequest)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	it.InternalFetch = func(pageSize int, pageToken string) ([]*multimediapb.LightNovel, string, error) {
		resp := &multimediapb.ListLightNovelsResponse{}
		if pageToken != "" {
			req.PageToken = pageToken
		}
		if pageSize > math.MaxInt32 {
			req.PageSize = math.MaxInt32
		} else if pageSize != 0 {
			req.PageSize = int32(pageSize)
		}
		baseUrl, err := url.Parse(c.endpoint)
		if err != nil {
			return nil, "", err
		}
		baseUrl.Path += fmt.Sprintf("/v1alpha1/lightNovels")

		params := url.Values{}
		if req.GetFilter() != "" {
			params.Add("filter", fmt.Sprintf("%v", req.GetFilter()))
		}
		if req.GetPageSize() != 0 {
			params.Add("pageSize", fmt.Sprintf("%v", req.GetPageSize()))
		}
		if req.GetPageToken() != "" {
			params.Add("pageToken", fmt.Sprintf("%v", req.GetPageToken()))
		}

		baseUrl.RawQuery = params.Encode()

		// Build HTTP headers from client and context metadata.
		headers := buildHeaders(ctx, c.xGoogMetadata, metadata.Pairs("Content-Type", "application/json"))
		e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
			if settings.Path != "" {
				baseUrl.Path = settings.Path
			}
			httpReq, err := http.NewRequest("GET", baseUrl.String(), nil)
			if err != nil {
				return err
			}
			httpReq.Header = headers

			httpRsp, err := c.httpClient.Do(httpReq)
			if err != nil {
				return err
			}
			defer httpRsp.Body.Close()

			if err = googleapi.CheckResponse(httpRsp); err != nil {
				return err
			}

			buf, err := ioutil.ReadAll(httpRsp.Body)
			if err != nil {
				return err
			}

			if err := unm.Unmarshal(buf, resp); err != nil {
				return maybeUnknownEnum(err)
			}

			return nil
		}, opts...)
		if e != nil {
			return nil, "", e
		}
		it.Response = resp
		return resp.GetLightNovels(), resp.GetNextPageToken(), nil
	}

	fetch := func(pageSize int, pageToken string) (string, error) {
		items, nextPageToken, err := it.InternalFetch(pageSize, pageToken)
		if err != nil {
			return "", err
		}
		it.items = append(it.items, items...)
		return nextPageToken, nil
	}

	it.pageInfo, it.nextFunc = iterator.NewPageInfo(fetch, it.bufLen, it.takeBuf)
	it.pageInfo.MaxSize = int(req.GetPageSize())
	it.pageInfo.Token = req.GetPageToken()

	return it
}
func (c *lightNovelRESTClient) CreateLightNovel(ctx context.Context, req *multimediapb.CreateLightNovelRequest, opts ...gax.CallOption) (*multimediapb.LightNovel, error) {
	m := protojson.MarshalOptions{AllowPartial: true, UseEnumNumbers: true}
	jsonReq, err := m.Marshal(req)
	if err != nil {
		return nil, err
	}

	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1alpha1/lightNovels")

	// Build HTTP headers from client and context metadata.
	headers := buildHeaders(ctx, c.xGoogMetadata, metadata.Pairs("Content-Type", "application/json"))
	opts = append((*c.CallOptions).CreateLightNovel[0:len((*c.CallOptions).CreateLightNovel):len((*c.CallOptions).CreateLightNovel)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &multimediapb.LightNovel{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("POST", baseUrl.String(), bytes.NewReader(jsonReq))
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := ioutil.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return maybeUnknownEnum(err)
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}
func (c *lightNovelRESTClient) UpdateLightNovel(ctx context.Context, req *multimediapb.UpdateLightNovelRequest, opts ...gax.CallOption) (*multimediapb.LightNovel, error) {
	m := protojson.MarshalOptions{AllowPartial: true, UseEnumNumbers: true}
	jsonReq, err := m.Marshal(req)
	if err != nil {
		return nil, err
	}

	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1alpha1/%v", req.GetLightNovel().GetName())

	// Build HTTP headers from client and context metadata.
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "light_novel.name", url.QueryEscape(req.GetLightNovel().GetName())))

	headers := buildHeaders(ctx, c.xGoogMetadata, md, metadata.Pairs("Content-Type", "application/json"))
	opts = append((*c.CallOptions).UpdateLightNovel[0:len((*c.CallOptions).UpdateLightNovel):len((*c.CallOptions).UpdateLightNovel)], opts...)
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &multimediapb.LightNovel{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("PATCH", baseUrl.String(), bytes.NewReader(jsonReq))
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := ioutil.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return maybeUnknownEnum(err)
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}
	return resp, nil
}
func (c *lightNovelRESTClient) DeleteLightNovel(ctx context.Context, req *multimediapb.DeleteLightNovelRequest, opts ...gax.CallOption) error {
	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return err
	}
	baseUrl.Path += fmt.Sprintf("/v1alpha1/%v", req.GetName())

	// Build HTTP headers from client and context metadata.
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))

	headers := buildHeaders(ctx, c.xGoogMetadata, md, metadata.Pairs("Content-Type", "application/json"))
	return gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("DELETE", baseUrl.String(), nil)
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		// Returns nil if there is no error, otherwise wraps
		// the response code and body into a non-nil error
		return googleapi.CheckResponse(httpRsp)
	}, opts...)
}

// ReconcileLightNovels reconcile light novels with the search and knowledge base.
func (c *lightNovelRESTClient) ReconcileLightNovels(ctx context.Context, req *multimediapb.ReconcileLightNovelsRequest, opts ...gax.CallOption) (*ReconcileLightNovelsOperation, error) {
	m := protojson.MarshalOptions{AllowPartial: true, UseEnumNumbers: true}
	jsonReq, err := m.Marshal(req)
	if err != nil {
		return nil, err
	}

	baseUrl, err := url.Parse(c.endpoint)
	if err != nil {
		return nil, err
	}
	baseUrl.Path += fmt.Sprintf("/v1alpha1/%v:reconcile", req.GetName())

	// Build HTTP headers from client and context metadata.
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))

	headers := buildHeaders(ctx, c.xGoogMetadata, md, metadata.Pairs("Content-Type", "application/json"))
	unm := protojson.UnmarshalOptions{AllowPartial: true, DiscardUnknown: true}
	resp := &longrunningpb.Operation{}
	e := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		if settings.Path != "" {
			baseUrl.Path = settings.Path
		}
		httpReq, err := http.NewRequest("POST", baseUrl.String(), bytes.NewReader(jsonReq))
		if err != nil {
			return err
		}
		httpReq = httpReq.WithContext(ctx)
		httpReq.Header = headers

		httpRsp, err := c.httpClient.Do(httpReq)
		if err != nil {
			return err
		}
		defer httpRsp.Body.Close()

		if err = googleapi.CheckResponse(httpRsp); err != nil {
			return err
		}

		buf, err := ioutil.ReadAll(httpRsp.Body)
		if err != nil {
			return err
		}

		if err := unm.Unmarshal(buf, resp); err != nil {
			return maybeUnknownEnum(err)
		}

		return nil
	}, opts...)
	if e != nil {
		return nil, e
	}

	override := fmt.Sprintf("/v1alpha1/%s", resp.GetName())
	return &ReconcileLightNovelsOperation{
		lro:      longrunning.InternalNewOperation(*c.LROClient, resp),
		pollPath: override,
	}, nil
}

// ReconcileLightNovelsOperation manages a long-running operation from ReconcileLightNovels.
type ReconcileLightNovelsOperation struct {
	lro      *longrunning.Operation
	pollPath string
}

// ReconcileLightNovelsOperation returns a new ReconcileLightNovelsOperation from a given name.
// The name must be that of a previously created ReconcileLightNovelsOperation, possibly from a different process.
func (c *lightNovelGRPCClient) ReconcileLightNovelsOperation(name string) *ReconcileLightNovelsOperation {
	return &ReconcileLightNovelsOperation{
		lro: longrunning.InternalNewOperation(*c.LROClient, &longrunningpb.Operation{Name: name}),
	}
}

// ReconcileLightNovelsOperation returns a new ReconcileLightNovelsOperation from a given name.
// The name must be that of a previously created ReconcileLightNovelsOperation, possibly from a different process.
func (c *lightNovelRESTClient) ReconcileLightNovelsOperation(name string) *ReconcileLightNovelsOperation {
	override := fmt.Sprintf("/v1alpha1/%s", name)
	return &ReconcileLightNovelsOperation{
		lro:      longrunning.InternalNewOperation(*c.LROClient, &longrunningpb.Operation{Name: name}),
		pollPath: override,
	}
}

// Wait blocks until the long-running operation is completed, returning the response and any errors encountered.
//
// See documentation of Poll for error-handling information.
func (op *ReconcileLightNovelsOperation) Wait(ctx context.Context, opts ...gax.CallOption) (*multimediapb.ReconcileLightNovelsResponse, error) {
	opts = append([]gax.CallOption{gax.WithPath(op.pollPath)}, opts...)
	var resp multimediapb.ReconcileLightNovelsResponse
	if err := op.lro.WaitWithInterval(ctx, &resp, time.Minute, opts...); err != nil {
		return nil, err
	}
	return &resp, nil
}

// Poll fetches the latest state of the long-running operation.
//
// Poll also fetches the latest metadata, which can be retrieved by Metadata.
//
// If Poll fails, the error is returned and op is unmodified. If Poll succeeds and
// the operation has completed with failure, the error is returned and op.Done will return true.
// If Poll succeeds and the operation has completed successfully,
// op.Done will return true, and the response of the operation is returned.
// If Poll succeeds and the operation has not completed, the returned response and error are both nil.
func (op *ReconcileLightNovelsOperation) Poll(ctx context.Context, opts ...gax.CallOption) (*multimediapb.ReconcileLightNovelsResponse, error) {
	opts = append([]gax.CallOption{gax.WithPath(op.pollPath)}, opts...)
	var resp multimediapb.ReconcileLightNovelsResponse
	if err := op.lro.Poll(ctx, &resp, opts...); err != nil {
		return nil, err
	}
	if !op.Done() {
		return nil, nil
	}
	return &resp, nil
}

// Metadata returns metadata associated with the long-running operation.
// Metadata itself does not contact the server, but Poll does.
// To get the latest metadata, call this method after a successful call to Poll.
// If the metadata is not available, the returned metadata and error are both nil.
func (op *ReconcileLightNovelsOperation) Metadata() (*multimediapb.OperationMetadata, error) {
	var meta multimediapb.OperationMetadata
	if err := op.lro.Metadata(&meta); err == longrunning.ErrNoMetadata {
		return nil, nil
	} else if err != nil {
		return nil, err
	}
	return &meta, nil
}

// Done reports whether the long-running operation has completed.
func (op *ReconcileLightNovelsOperation) Done() bool {
	return op.lro.Done()
}

// Name returns the name of the long-running operation.
// The name is assigned by the server and is unique within the service from which the operation is created.
func (op *ReconcileLightNovelsOperation) Name() string {
	return op.lro.Name()
}

// LightNovelIterator manages a stream of *multimediapb.LightNovel.
type LightNovelIterator struct {
	items    []*multimediapb.LightNovel
	pageInfo *iterator.PageInfo
	nextFunc func() error

	// Response is the raw response for the current page.
	// It must be cast to the RPC response type.
	// Calling Next() or InternalFetch() updates this value.
	Response interface{}

	// InternalFetch is for use by the Google Cloud Libraries only.
	// It is not part of the stable interface of this package.
	//
	// InternalFetch returns results from a single call to the underlying RPC.
	// The number of results is no greater than pageSize.
	// If there are no more results, nextPageToken is empty and err is nil.
	InternalFetch func(pageSize int, pageToken string) (results []*multimediapb.LightNovel, nextPageToken string, err error)
}

// PageInfo supports pagination. See the google.golang.org/api/iterator package for details.
func (it *LightNovelIterator) PageInfo() *iterator.PageInfo {
	return it.pageInfo
}

// Next returns the next result. Its second return value is iterator.Done if there are no more
// results. Once Next returns Done, all subsequent calls will return Done.
func (it *LightNovelIterator) Next() (*multimediapb.LightNovel, error) {
	var item *multimediapb.LightNovel
	if err := it.nextFunc(); err != nil {
		return item, err
	}
	item = it.items[0]
	it.items = it.items[1:]
	return item, nil
}

func (it *LightNovelIterator) bufLen() int {
	return len(it.items)
}

func (it *LightNovelIterator) takeBuf() interface{} {
	b := it.items
	it.items = nil
	return b
}
