// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package grbac

import (
	"context"
	"fmt"
	"math"
	"net/url"

	grbacpb "github.com/animeapis/go-genproto/grbac/v1alpha1"
	gax "github.com/googleapis/gax-go/v2"
	"google.golang.org/api/option"
	"google.golang.org/api/option/internaloption"
	gtransport "google.golang.org/api/transport/grpc"
	iampb "google.golang.org/genproto/googleapis/iam/v1"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
)

var newAccessControlClientHook clientHook

// AccessControlCallOptions contains the retry settings for each method of AccessControlClient.
type AccessControlCallOptions struct {
	TestIamPolicy     []gax.CallOption
	GetIamPolicy      []gax.CallOption
	SetIamPolicy      []gax.CallOption
	GetResource       []gax.CallOption
	CreateResource    []gax.CallOption
	TransferResource  []gax.CallOption
	DeleteResource    []gax.CallOption
	CreateSubject     []gax.CallOption
	DeleteSubject     []gax.CallOption
	GetGroup          []gax.CallOption
	CreateGroup       []gax.CallOption
	UpdateGroup       []gax.CallOption
	AddGroupMember    []gax.CallOption
	RemoveGroupMember []gax.CallOption
	DeleteGroup       []gax.CallOption
	CreatePermission  []gax.CallOption
	DeletePermission  []gax.CallOption
	GetRole           []gax.CallOption
	CreateRole        []gax.CallOption
	UpdateRole        []gax.CallOption
	DeleteRole        []gax.CallOption
}

func defaultAccessControlGRPCClientOptions() []option.ClientOption {
	return []option.ClientOption{
		internaloption.WithDefaultEndpoint("127.0.0.1:9080"),
		internaloption.WithDefaultMTLSEndpoint("127.0.0.1:9080"),
		internaloption.WithDefaultAudience("https://127.0.0.1/"),
		internaloption.WithDefaultScopes(DefaultAuthScopes()...),
		option.WithGRPCDialOption(grpc.WithDisableServiceConfig()),
		option.WithGRPCDialOption(grpc.WithDefaultCallOptions(
			grpc.MaxCallRecvMsgSize(math.MaxInt32))),
	}
}

func defaultAccessControlCallOptions() *AccessControlCallOptions {
	return &AccessControlCallOptions{
		TestIamPolicy:     []gax.CallOption{},
		GetIamPolicy:      []gax.CallOption{},
		SetIamPolicy:      []gax.CallOption{},
		GetResource:       []gax.CallOption{},
		CreateResource:    []gax.CallOption{},
		TransferResource:  []gax.CallOption{},
		DeleteResource:    []gax.CallOption{},
		CreateSubject:     []gax.CallOption{},
		DeleteSubject:     []gax.CallOption{},
		GetGroup:          []gax.CallOption{},
		CreateGroup:       []gax.CallOption{},
		UpdateGroup:       []gax.CallOption{},
		AddGroupMember:    []gax.CallOption{},
		RemoveGroupMember: []gax.CallOption{},
		DeleteGroup:       []gax.CallOption{},
		CreatePermission:  []gax.CallOption{},
		DeletePermission:  []gax.CallOption{},
		GetRole:           []gax.CallOption{},
		CreateRole:        []gax.CallOption{},
		UpdateRole:        []gax.CallOption{},
		DeleteRole:        []gax.CallOption{},
	}
}

// internalAccessControlClient is an interface that defines the methods availaible from gRBAC API.
type internalAccessControlClient interface {
	Close() error
	setGoogleClientInfo(...string)
	Connection() *grpc.ClientConn
	TestIamPolicy(context.Context, *grbacpb.TestIamPolicyRequest, ...gax.CallOption) error
	GetIamPolicy(context.Context, *iampb.GetIamPolicyRequest, ...gax.CallOption) (*iampb.Policy, error)
	SetIamPolicy(context.Context, *iampb.SetIamPolicyRequest, ...gax.CallOption) (*iampb.Policy, error)
	GetResource(context.Context, *grbacpb.GetResourceRequest, ...gax.CallOption) (*grbacpb.Resource, error)
	CreateResource(context.Context, *grbacpb.CreateResourceRequest, ...gax.CallOption) (*grbacpb.Resource, error)
	TransferResource(context.Context, *grbacpb.TransferResourceRequest, ...gax.CallOption) (*grbacpb.Resource, error)
	DeleteResource(context.Context, *grbacpb.DeleteResourceRequest, ...gax.CallOption) error
	CreateSubject(context.Context, *grbacpb.CreateSubjectRequest, ...gax.CallOption) (*grbacpb.Subject, error)
	DeleteSubject(context.Context, *grbacpb.DeleteSubjectRequest, ...gax.CallOption) error
	GetGroup(context.Context, *grbacpb.GetGroupRequest, ...gax.CallOption) (*grbacpb.Group, error)
	CreateGroup(context.Context, *grbacpb.CreateGroupRequest, ...gax.CallOption) (*grbacpb.Group, error)
	UpdateGroup(context.Context, *grbacpb.UpdateGroupRequest, ...gax.CallOption) (*grbacpb.Group, error)
	AddGroupMember(context.Context, *grbacpb.AddGroupMemberRequest, ...gax.CallOption) (*grbacpb.Group, error)
	RemoveGroupMember(context.Context, *grbacpb.RemoveGroupMemberRequest, ...gax.CallOption) (*grbacpb.Group, error)
	DeleteGroup(context.Context, *grbacpb.DeleteGroupRequest, ...gax.CallOption) error
	CreatePermission(context.Context, *grbacpb.CreatePermissionRequest, ...gax.CallOption) (*grbacpb.Permission, error)
	DeletePermission(context.Context, *grbacpb.DeletePermissionRequest, ...gax.CallOption) error
	GetRole(context.Context, *grbacpb.GetRoleRequest, ...gax.CallOption) (*grbacpb.Role, error)
	CreateRole(context.Context, *grbacpb.CreateRoleRequest, ...gax.CallOption) (*grbacpb.Role, error)
	UpdateRole(context.Context, *grbacpb.UpdateRoleRequest, ...gax.CallOption) (*grbacpb.Role, error)
	DeleteRole(context.Context, *grbacpb.DeleteRoleRequest, ...gax.CallOption) error
}

// AccessControlClient is a client for interacting with gRBAC API.
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
//
// AccessControl is the internal service used by Animeshon to enforce RBAC rules.
type AccessControlClient struct {
	// The internal transport-dependent client.
	internalClient internalAccessControlClient

	// The call options for this service.
	CallOptions *AccessControlCallOptions
}

// Wrapper methods routed to the internal client.

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *AccessControlClient) Close() error {
	return c.internalClient.Close()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *AccessControlClient) setGoogleClientInfo(keyval ...string) {
	c.internalClient.setGoogleClientInfo(keyval...)
}

// Connection returns a connection to the API service.
//
// Deprecated.
func (c *AccessControlClient) Connection() *grpc.ClientConn {
	return c.internalClient.Connection()
}

// TestIamPolicy checks whether a member has a specific permission for a specific resource.
// If not allowed an Unauthorized (403) error will be returned.
func (c *AccessControlClient) TestIamPolicy(ctx context.Context, req *grbacpb.TestIamPolicyRequest, opts ...gax.CallOption) error {
	return c.internalClient.TestIamPolicy(ctx, req, opts...)
}

// GetIamPolicy gets the IAM policy that is attached to a generic resource.
// Note: the full resource name that identifies the resource must be provided.
func (c *AccessControlClient) GetIamPolicy(ctx context.Context, req *iampb.GetIamPolicyRequest, opts ...gax.CallOption) (*iampb.Policy, error) {
	return c.internalClient.GetIamPolicy(ctx, req, opts...)
}

// SetIamPolicy sets the IAM policy that is attached to a generic resource.
// Note: the full resource name that identifies the resource must be provided.
func (c *AccessControlClient) SetIamPolicy(ctx context.Context, req *iampb.SetIamPolicyRequest, opts ...gax.CallOption) (*iampb.Policy, error) {
	return c.internalClient.SetIamPolicy(ctx, req, opts...)
}

// GetResource getResource returns a resource.
func (c *AccessControlClient) GetResource(ctx context.Context, req *grbacpb.GetResourceRequest, opts ...gax.CallOption) (*grbacpb.Resource, error) {
	return c.internalClient.GetResource(ctx, req, opts...)
}

// CreateResource createResource creates a new resource.
func (c *AccessControlClient) CreateResource(ctx context.Context, req *grbacpb.CreateResourceRequest, opts ...gax.CallOption) (*grbacpb.Resource, error) {
	return c.internalClient.CreateResource(ctx, req, opts...)
}

// TransferResource transferResource transfers a resource to a new parent.
func (c *AccessControlClient) TransferResource(ctx context.Context, req *grbacpb.TransferResourceRequest, opts ...gax.CallOption) (*grbacpb.Resource, error) {
	return c.internalClient.TransferResource(ctx, req, opts...)
}

// DeleteResource deleteResource deletes a resource.
func (c *AccessControlClient) DeleteResource(ctx context.Context, req *grbacpb.DeleteResourceRequest, opts ...gax.CallOption) error {
	return c.internalClient.DeleteResource(ctx, req, opts...)
}

// CreateSubject createSubject creates a new subject.
func (c *AccessControlClient) CreateSubject(ctx context.Context, req *grbacpb.CreateSubjectRequest, opts ...gax.CallOption) (*grbacpb.Subject, error) {
	return c.internalClient.CreateSubject(ctx, req, opts...)
}

// DeleteSubject deleteSubject deletes a subject.
func (c *AccessControlClient) DeleteSubject(ctx context.Context, req *grbacpb.DeleteSubjectRequest, opts ...gax.CallOption) error {
	return c.internalClient.DeleteSubject(ctx, req, opts...)
}

// GetGroup getGroup returns a group.
func (c *AccessControlClient) GetGroup(ctx context.Context, req *grbacpb.GetGroupRequest, opts ...gax.CallOption) (*grbacpb.Group, error) {
	return c.internalClient.GetGroup(ctx, req, opts...)
}

// CreateGroup createGroup creates a new group.
func (c *AccessControlClient) CreateGroup(ctx context.Context, req *grbacpb.CreateGroupRequest, opts ...gax.CallOption) (*grbacpb.Group, error) {
	return c.internalClient.CreateGroup(ctx, req, opts...)
}

// UpdateGroup updateGroup updates a group with a field mask.
func (c *AccessControlClient) UpdateGroup(ctx context.Context, req *grbacpb.UpdateGroupRequest, opts ...gax.CallOption) (*grbacpb.Group, error) {
	return c.internalClient.UpdateGroup(ctx, req, opts...)
}

// AddGroupMember addGroupMember adds a member to a group.
func (c *AccessControlClient) AddGroupMember(ctx context.Context, req *grbacpb.AddGroupMemberRequest, opts ...gax.CallOption) (*grbacpb.Group, error) {
	return c.internalClient.AddGroupMember(ctx, req, opts...)
}

// RemoveGroupMember removeGroupMember removes a member from a group.
func (c *AccessControlClient) RemoveGroupMember(ctx context.Context, req *grbacpb.RemoveGroupMemberRequest, opts ...gax.CallOption) (*grbacpb.Group, error) {
	return c.internalClient.RemoveGroupMember(ctx, req, opts...)
}

// DeleteGroup deleteGroup deletes a group.
func (c *AccessControlClient) DeleteGroup(ctx context.Context, req *grbacpb.DeleteGroupRequest, opts ...gax.CallOption) error {
	return c.internalClient.DeleteGroup(ctx, req, opts...)
}

// CreatePermission createPermission creates a new permission.
func (c *AccessControlClient) CreatePermission(ctx context.Context, req *grbacpb.CreatePermissionRequest, opts ...gax.CallOption) (*grbacpb.Permission, error) {
	return c.internalClient.CreatePermission(ctx, req, opts...)
}

// DeletePermission deletePermission deletes a permission.
func (c *AccessControlClient) DeletePermission(ctx context.Context, req *grbacpb.DeletePermissionRequest, opts ...gax.CallOption) error {
	return c.internalClient.DeletePermission(ctx, req, opts...)
}

// GetRole getRole returns a role.
func (c *AccessControlClient) GetRole(ctx context.Context, req *grbacpb.GetRoleRequest, opts ...gax.CallOption) (*grbacpb.Role, error) {
	return c.internalClient.GetRole(ctx, req, opts...)
}

// CreateRole createRole creates a new role.
func (c *AccessControlClient) CreateRole(ctx context.Context, req *grbacpb.CreateRoleRequest, opts ...gax.CallOption) (*grbacpb.Role, error) {
	return c.internalClient.CreateRole(ctx, req, opts...)
}

// UpdateRole updateRole updates a role with a field mask.
func (c *AccessControlClient) UpdateRole(ctx context.Context, req *grbacpb.UpdateRoleRequest, opts ...gax.CallOption) (*grbacpb.Role, error) {
	return c.internalClient.UpdateRole(ctx, req, opts...)
}

// DeleteRole deleteRole deletes a role.
func (c *AccessControlClient) DeleteRole(ctx context.Context, req *grbacpb.DeleteRoleRequest, opts ...gax.CallOption) error {
	return c.internalClient.DeleteRole(ctx, req, opts...)
}

// accessControlGRPCClient is a client for interacting with gRBAC API over gRPC transport.
//
// Methods, except Close, may be called concurrently. However, fields must not be modified concurrently with method calls.
type accessControlGRPCClient struct {
	// Connection pool of gRPC connections to the service.
	connPool gtransport.ConnPool

	// flag to opt out of default deadlines via GOOGLE_API_GO_EXPERIMENTAL_DISABLE_DEFAULT_DEADLINE
	disableDeadlines bool

	// Points back to the CallOptions field of the containing AccessControlClient
	CallOptions **AccessControlCallOptions

	// The gRPC API client.
	accessControlClient grbacpb.AccessControlClient

	// The x-goog-* metadata to be sent with each request.
	xGoogMetadata metadata.MD
}

// NewAccessControlClient creates a new access control client based on gRPC.
// The returned client must be Closed when it is done being used to clean up its underlying connections.
//
// AccessControl is the internal service used by Animeshon to enforce RBAC rules.
func NewAccessControlClient(ctx context.Context, opts ...option.ClientOption) (*AccessControlClient, error) {
	clientOpts := defaultAccessControlGRPCClientOptions()
	if newAccessControlClientHook != nil {
		hookOpts, err := newAccessControlClientHook(ctx, clientHookParams{})
		if err != nil {
			return nil, err
		}
		clientOpts = append(clientOpts, hookOpts...)
	}

	disableDeadlines, err := checkDisableDeadlines()
	if err != nil {
		return nil, err
	}

	connPool, err := gtransport.DialPool(ctx, append(clientOpts, opts...)...)
	if err != nil {
		return nil, err
	}
	client := AccessControlClient{CallOptions: defaultAccessControlCallOptions()}

	c := &accessControlGRPCClient{
		connPool:            connPool,
		disableDeadlines:    disableDeadlines,
		accessControlClient: grbacpb.NewAccessControlClient(connPool),
		CallOptions:         &client.CallOptions,
	}
	c.setGoogleClientInfo()

	client.internalClient = c

	return &client, nil
}

// Connection returns a connection to the API service.
//
// Deprecated.
func (c *accessControlGRPCClient) Connection() *grpc.ClientConn {
	return c.connPool.Conn()
}

// setGoogleClientInfo sets the name and version of the application in
// the `x-goog-api-client` header passed on each request. Intended for
// use by Google-written clients.
func (c *accessControlGRPCClient) setGoogleClientInfo(keyval ...string) {
	kv := append([]string{"gl-go", versionGo()}, keyval...)
	kv = append(kv, "gapic", versionClient, "gax", gax.Version, "grpc", grpc.Version)
	c.xGoogMetadata = metadata.Pairs("x-goog-api-client", gax.XGoogHeader(kv...))
}

// Close closes the connection to the API service. The user should invoke this when
// the client is no longer required.
func (c *accessControlGRPCClient) Close() error {
	return c.connPool.Close()
}

func (c *accessControlGRPCClient) TestIamPolicy(ctx context.Context, req *grbacpb.TestIamPolicyRequest, opts ...gax.CallOption) error {
	ctx = insertMetadata(ctx, c.xGoogMetadata)
	opts = append((*c.CallOptions).TestIamPolicy[0:len((*c.CallOptions).TestIamPolicy):len((*c.CallOptions).TestIamPolicy)], opts...)
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		_, err = c.accessControlClient.TestIamPolicy(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	return err
}

func (c *accessControlGRPCClient) GetIamPolicy(ctx context.Context, req *iampb.GetIamPolicyRequest, opts ...gax.CallOption) (*iampb.Policy, error) {
	ctx = insertMetadata(ctx, c.xGoogMetadata)
	opts = append((*c.CallOptions).GetIamPolicy[0:len((*c.CallOptions).GetIamPolicy):len((*c.CallOptions).GetIamPolicy)], opts...)
	var resp *iampb.Policy
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.GetIamPolicy(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) SetIamPolicy(ctx context.Context, req *iampb.SetIamPolicyRequest, opts ...gax.CallOption) (*iampb.Policy, error) {
	ctx = insertMetadata(ctx, c.xGoogMetadata)
	opts = append((*c.CallOptions).SetIamPolicy[0:len((*c.CallOptions).SetIamPolicy):len((*c.CallOptions).SetIamPolicy)], opts...)
	var resp *iampb.Policy
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.SetIamPolicy(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) GetResource(ctx context.Context, req *grbacpb.GetResourceRequest, opts ...gax.CallOption) (*grbacpb.Resource, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).GetResource[0:len((*c.CallOptions).GetResource):len((*c.CallOptions).GetResource)], opts...)
	var resp *grbacpb.Resource
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.GetResource(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) CreateResource(ctx context.Context, req *grbacpb.CreateResourceRequest, opts ...gax.CallOption) (*grbacpb.Resource, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "resource.name", url.QueryEscape(req.GetResource().GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).CreateResource[0:len((*c.CallOptions).CreateResource):len((*c.CallOptions).CreateResource)], opts...)
	var resp *grbacpb.Resource
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.CreateResource(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) TransferResource(ctx context.Context, req *grbacpb.TransferResourceRequest, opts ...gax.CallOption) (*grbacpb.Resource, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).TransferResource[0:len((*c.CallOptions).TransferResource):len((*c.CallOptions).TransferResource)], opts...)
	var resp *grbacpb.Resource
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.TransferResource(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) DeleteResource(ctx context.Context, req *grbacpb.DeleteResourceRequest, opts ...gax.CallOption) error {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).DeleteResource[0:len((*c.CallOptions).DeleteResource):len((*c.CallOptions).DeleteResource)], opts...)
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		_, err = c.accessControlClient.DeleteResource(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	return err
}

func (c *accessControlGRPCClient) CreateSubject(ctx context.Context, req *grbacpb.CreateSubjectRequest, opts ...gax.CallOption) (*grbacpb.Subject, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "subject.name", url.QueryEscape(req.GetSubject().GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).CreateSubject[0:len((*c.CallOptions).CreateSubject):len((*c.CallOptions).CreateSubject)], opts...)
	var resp *grbacpb.Subject
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.CreateSubject(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) DeleteSubject(ctx context.Context, req *grbacpb.DeleteSubjectRequest, opts ...gax.CallOption) error {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).DeleteSubject[0:len((*c.CallOptions).DeleteSubject):len((*c.CallOptions).DeleteSubject)], opts...)
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		_, err = c.accessControlClient.DeleteSubject(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	return err
}

func (c *accessControlGRPCClient) GetGroup(ctx context.Context, req *grbacpb.GetGroupRequest, opts ...gax.CallOption) (*grbacpb.Group, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).GetGroup[0:len((*c.CallOptions).GetGroup):len((*c.CallOptions).GetGroup)], opts...)
	var resp *grbacpb.Group
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.GetGroup(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) CreateGroup(ctx context.Context, req *grbacpb.CreateGroupRequest, opts ...gax.CallOption) (*grbacpb.Group, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "group.name", url.QueryEscape(req.GetGroup().GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).CreateGroup[0:len((*c.CallOptions).CreateGroup):len((*c.CallOptions).CreateGroup)], opts...)
	var resp *grbacpb.Group
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.CreateGroup(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) UpdateGroup(ctx context.Context, req *grbacpb.UpdateGroupRequest, opts ...gax.CallOption) (*grbacpb.Group, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "group.name", url.QueryEscape(req.GetGroup().GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).UpdateGroup[0:len((*c.CallOptions).UpdateGroup):len((*c.CallOptions).UpdateGroup)], opts...)
	var resp *grbacpb.Group
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.UpdateGroup(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) AddGroupMember(ctx context.Context, req *grbacpb.AddGroupMemberRequest, opts ...gax.CallOption) (*grbacpb.Group, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "group", url.QueryEscape(req.GetGroup())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).AddGroupMember[0:len((*c.CallOptions).AddGroupMember):len((*c.CallOptions).AddGroupMember)], opts...)
	var resp *grbacpb.Group
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.AddGroupMember(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) RemoveGroupMember(ctx context.Context, req *grbacpb.RemoveGroupMemberRequest, opts ...gax.CallOption) (*grbacpb.Group, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "group", url.QueryEscape(req.GetGroup())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).RemoveGroupMember[0:len((*c.CallOptions).RemoveGroupMember):len((*c.CallOptions).RemoveGroupMember)], opts...)
	var resp *grbacpb.Group
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.RemoveGroupMember(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) DeleteGroup(ctx context.Context, req *grbacpb.DeleteGroupRequest, opts ...gax.CallOption) error {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).DeleteGroup[0:len((*c.CallOptions).DeleteGroup):len((*c.CallOptions).DeleteGroup)], opts...)
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		_, err = c.accessControlClient.DeleteGroup(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	return err
}

func (c *accessControlGRPCClient) CreatePermission(ctx context.Context, req *grbacpb.CreatePermissionRequest, opts ...gax.CallOption) (*grbacpb.Permission, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "permission.name", url.QueryEscape(req.GetPermission().GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).CreatePermission[0:len((*c.CallOptions).CreatePermission):len((*c.CallOptions).CreatePermission)], opts...)
	var resp *grbacpb.Permission
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.CreatePermission(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) DeletePermission(ctx context.Context, req *grbacpb.DeletePermissionRequest, opts ...gax.CallOption) error {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).DeletePermission[0:len((*c.CallOptions).DeletePermission):len((*c.CallOptions).DeletePermission)], opts...)
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		_, err = c.accessControlClient.DeletePermission(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	return err
}

func (c *accessControlGRPCClient) GetRole(ctx context.Context, req *grbacpb.GetRoleRequest, opts ...gax.CallOption) (*grbacpb.Role, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).GetRole[0:len((*c.CallOptions).GetRole):len((*c.CallOptions).GetRole)], opts...)
	var resp *grbacpb.Role
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.GetRole(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) CreateRole(ctx context.Context, req *grbacpb.CreateRoleRequest, opts ...gax.CallOption) (*grbacpb.Role, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "role.name", url.QueryEscape(req.GetRole().GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).CreateRole[0:len((*c.CallOptions).CreateRole):len((*c.CallOptions).CreateRole)], opts...)
	var resp *grbacpb.Role
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.CreateRole(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) UpdateRole(ctx context.Context, req *grbacpb.UpdateRoleRequest, opts ...gax.CallOption) (*grbacpb.Role, error) {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "role.name", url.QueryEscape(req.GetRole().GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).UpdateRole[0:len((*c.CallOptions).UpdateRole):len((*c.CallOptions).UpdateRole)], opts...)
	var resp *grbacpb.Role
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		resp, err = c.accessControlClient.UpdateRole(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *accessControlGRPCClient) DeleteRole(ctx context.Context, req *grbacpb.DeleteRoleRequest, opts ...gax.CallOption) error {
	md := metadata.Pairs("x-goog-request-params", fmt.Sprintf("%s=%v", "name", url.QueryEscape(req.GetName())))
	ctx = insertMetadata(ctx, c.xGoogMetadata, md)
	opts = append((*c.CallOptions).DeleteRole[0:len((*c.CallOptions).DeleteRole):len((*c.CallOptions).DeleteRole)], opts...)
	err := gax.Invoke(ctx, func(ctx context.Context, settings gax.CallSettings) error {
		var err error
		_, err = c.accessControlClient.DeleteRole(ctx, req, settings.GRPC...)
		return err
	}, opts...)
	return err
}
